endpoint:
  ms-data-access:
    protocol: ${PROTOCOL_DATA:http}
    host: ${HOST_DATA:localhost}
    port: ${PORT_DATA:5005}
qr:
  path: /Users/nicolas/Documents/repo_qr/
mail:
  configuration:
    user: admin@compraboletas.shop
    password: Nicole1310*
business:
  pathRepo: ${BUSINESS_PATH_IMAGES:/Users/nicolas/Documents/repo_images/}
logging:
  level:
    co:
      com:
        entrando:
          business:
            client: debug