spring:
  liquibase:
    change-log: classpath:db/db.changelog.xml

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
