spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      loadbalancer:
        ribbon:
          enabled: false
      routes:
        - id: acceso-datos
          uri: lb://entrando-acceso-datos
          predicates:
          - Path=/entrando-acceso-datos/**
          filters:
          - PreserveHostHeader
        - id: business
          uri: lb://entrando-business
          predicates:
          - Path=/api-business/**
          filters:
          - PreserveHostHeader
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG