spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      loadbalancer:
        ribbon:
          enabled: false
      routes:
        - id: acceso-datos
          uri: lb://entrando-acceso-datos
          predicates:
          - Path=/api-acceso-datos/**
          filters:
          - PreserveHostHeader
        - id: business
          uri: lb://entrando-business
          predicates:
          - Path=/api-business/**
          filters:
          - PreserveHostHeader
        - id: public
          uri: lb://entrando-public-users
          predicates:
            - Path=/api-public-users/**
          filters:
            - PreserveHostHeader
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG