#########################
# INFRASTRUCTURE
#########################
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5433:5432
    volumes:
      - ${VOL_PG}:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: S3cret
      POSTGRES_USER: hashticket
      POSTGRES_DB: tickero
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U hashticket -d tickero" ]
      interval: 10s
      timeout: 5s
      retries: 5
  postgreskc:
    image: postgres:16-alpine
    ports:
      - 5434:5432
    volumes:
      - ${VOL_PG_KC}:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.2
    command: start
    restart: always
    ports:
      - "8080:8080"
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgreskc:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
#########################
# SERVICE
#########################