networks:
  keycloak-network:
    driver: bridge
#########################
# INFRASTRUCTURE
#########################
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5435:5432
    volumes:
      - ${VOL_PG}:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: S3cret
      POSTGRES_USER: hashticket
      POSTGRES_DB: tickero
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U hashticket -d tickero" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - entrando-network
  postgreskc:
    image: postgres:16-alpine
    ports:
      - 5436:5432
    volumes:
      - ${VOL_PG_KC}:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak_db_user -d keycloak_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - keycloak-network
  keycloak:
    image: keycloak-custom
    command: start
      --optimized
      --hostname=auth.iaticket.net
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_DB_URL: jdbc:postgresql://postgreskc:5432/${POSTGRES_DB}
      KC_DB_POOL_MIN_SIZE: 5
      KC_DB_POOL_MAX_SIZE: 15
      KC_HOSTNAME_URL: https://auth.iaticket.net:8443/
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/server.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/server.key
      JAVA_OPTS: >-
        -XX:+UseG1GC
        -XX:MaxGCPauseMillis=500
        -XX:+UseStringDeduplication
        -Xms512m
        -Xmx1024m
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/8443' || exit 1
      interval: 5s
      timeout: 2s
      retries: 200
      start_period: 20s
    networks:
      - keycloak-network
    depends_on:
      postgreskc:
        condition: service_healthy
    volumes:
      - ./etc/certs/server.crt:/opt/keycloak/conf/server.crt
      - ./etc/certs/server.key:/opt/keycloak/conf/server.key
    deploy:
      resources:
        limits:
          memory: 1536M
        reservations:
          memory: 512M
#########################
# SERVICE CLOUD
#########################
  entrando-discovery:
    image: 46.202.92.9:5000/entrando-discovery:0.0.1-SNAPSHOT
    container_name: entrando-discovery
    ports:
      - "8762:8761"
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/8761' || exit 1
      interval: 2s
      timeout: 2s
      retries: 100
      start_period: 10s
    networks:
      - entrando-network