server:
  port: 8888

spring:
  application:
    name: entrando-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/config/security
            - classpath:/config/datos
            - classpath:/config/discovery
            - classpath:/config/business
            - classpath:/config/tracing
            - classpath:/config/mail